// Bundle the serverless entry into plain ESM so Vercel's Node runtime needs no TypeScript step.
// We only use libSQL over HTTP, so the CommonJS WebSocket transport (ws) is stubbed out:
// bundling it caused `Dynamic require of "events"` at runtime.
import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
mkdirSync('api', { recursive: true });
writeFileSync('scripts/ws-stub.js', 'export default class WebSocketUnavailable { constructor() { throw new Error("WebSocket transport disabled; use https:// libsql URLs"); } }\nexport const WebSocket = WebSocketUnavailable;\n');
await build({
  entryPoints: ['server/vercel-entry.ts'],
  outfile: 'api/index.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  legalComments: 'none',
  external: ['node:*'],
  alias: { ws: './scripts/ws-stub.js', '@libsql/isomorphic-ws': './scripts/ws-stub.js' },
  banner: { js: '// generated by scripts/build-vercel.mjs — do not edit' },
});
console.log('built api/index.js (esm)');
