// SPDX-License-Identifier: BUSL-1.1
// Bundle the serverless entry into plain ESM so Vercel's Node runtime needs no TypeScript step.
// We only use libSQL over HTTP, so the CommonJS WebSocket transport (ws) is stubbed out:
// bundling it caused `Dynamic require of "events"` at runtime.
import { build } from 'esbuild';
import { cpSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
mkdirSync('api', { recursive: true });
writeFileSync('scripts/ws-stub.js', 'export default class WebSocketUnavailable { constructor() { throw new Error("WebSocket transport disabled; use https:// libsql URLs"); } }\nexport const WebSocket = WebSocketUnavailable;\n');
await build({
  entryPoints: ['server/vercel-entry.ts'],
  outfile: 'api/index.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  legalComments: 'none',
  external: ['node:*'],
  alias: { ws: './scripts/ws-stub.js', '@libsql/isomorphic-ws': './scripts/ws-stub.js' },
  banner: { js: '// generated by scripts/build-vercel.mjs — do not edit' },
});
console.log('built api/index.js (esm)');

// Static files go to Vercel's CDN (public/ is served before the function), so page assets never start the function
// and a flood of asset requests costs nothing. Pages stay in the function (they carry session ids, headers, access
// checks); the operators' view (ops.*) is never public.
const STATIC = /\.(css|js|svg|png|ico|webp|jpg|woff2?|txt|webmanifest)$/;
mkdirSync('public/sdk', { recursive: true });
let n = 0;
for (const f of readdirSync('web')) if (STATIC.test(f) && !f.startsWith('ops.')) { cpSync(`web/${f}`, `public/${f}`); n++; }
cpSync('sdk/onehuman.js', 'public/sdk/onehuman.js');
console.log(`copied ${n} static files and the SDK to public/ (CDN)`);
